# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todocontent',
            name='ischecked',
            field=models.BooleanField(default=False, verbose_name='选择状态'),
        ),
    ]
