# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todocontent_ischecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='todocontent',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='激活状态'),
        ),
        migrations.AlterField(
            model_name='todocontent',
            name='ischecked',
            field=models.BooleanField(default=False, verbose_name='选中状态'),
        ),
    ]
